version: '3.8'

services:
  # application-backend:
  # build: .
  # command: bash -c "npm run build && npm run start:application:backend"
  # depends_on:
  # - kibana
  # - elasticsearch
  #  - rabbitmq
  # volumes:
  #  - .:/code:delegated
  # ports:
  # - 5000:5000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: promed-encoder-elasticsearch
    environment:
      - node.name=promed-encoder-elasticsearch
      - discovery.type=single-node #Elasticsearch forms a single-node cluster
      - bootstrap.memory_lock=true # might cause the JVM or shell session to exit if it tries to allocate more memory than is available!
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1 # The memlock soft and hard values configures the range of memory that ElasticSearch will use. Setting this to –1 means unlimited.
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: promed-encoder-kibana
    environment:
      ELASTICSEARCH_URL: http://promed-encoder-elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://promed-encoder-elasticsearch:9200
    ports:
      - 5601:5601

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  node_modules:
  esdata:
    driver: local
